management:
  context-path: /sysinfo
  endpoint:
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
#  management.metrics.export.{system}.enabled=false
spring:
    main:
        banner-mode: off
    security:
        lacale: pl_PL
    output:
        ansi:
            enabled: ALWAYS
    jpa:
        database: MYSQL
#        show-sql: true
        properties:
            hibernate:
#                format_sql: true
                dialect: org.hibernate.dialect.MySQL5Dialect
                hbm2ddl:
                  import_files: import_data.sql
        hibernate:
            ddl-auto: update
    datasource:
        url: jdbc:mysql://db.rp.e-strix.pl:3307/zwroty_e_strix_com?useUnicode=yes&characterEncoding=UTF-8
        username: user
        password: user
        driver-class-name: com.mysql.jdbc.Driver
        testWhileIdle: true
        testOnBorrow: true
        validationQuery: SELECT 1
hibernate:
    archive:
        autodetection: class
logging:
    level:
        org:
#            springframework:
#                data: ERROR
#            hibernate:
#                type: trace
#                descriptor:
#                    sql: trace
        pl:
            estrix: trace
    pattern:
#        console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
        file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: /tmp/application.log
server:
    port : 8882
    session-timeout : 1800


