export const ACTION_TYPE = {
    FETCH_START: "FETCH_START",
    FETCH_SUCCESS: "FETCH_SUCCESS",
    FETCH_SINGLE_SUCCESS: "FETCH_SINGLE_SUCCESS",
    FETCH_DELETE_SUCCESS: "FETCH_DELETE_SUCCESS",
    FETCH_POSUP_SUCCESS: "FETCH_POSUP_SUCCESS",
    FETCH_ERROR: "FETCH_ERROR"
}