#!/bin/bash
set -e # Exit on failure

source $(dirname $0)/lib/logging

log INFO "Prepare D3S Server"
#ENTRYPOINT ["java", "-XX:+UseContainerSupport", "-XX:MaxRAMPercentage=75.0", "-XX:+UseG1GC", "-XX:+UseStringDeduplication", "-XX:+ExitOnOutOfMemoryError", "-jar", "/opt/app/d3s/http-executor-starter.jar", "--spring.config.location=/opt/app/d3s/config/"]

java -XX:+UseContainerSupport -XX:MaxRAMPercentage=75.0 -XX:+UseG1GC -XX:+UseStringDeduplication -XX:+ExitOnOutOfMemoryError -jar /opt/app/d3s/web-ui-starter.jar
