def runShell(String command){
    def responseCode = sh returnStatus: true, script: "${command} &> tmp.txt"
    def output =  readFile(file: "tmp.txt")
    return (output != "")
}

def buildTime() {
    new Date().format('yyyy.MM.dd HH:mm')
}

pipeline {
    agent any
    environment {
        CURRENT_TIME = buildTime()
        PATH = "$PATH:/usr/local/bin"
      }

    parameters {
        string(name: 'version_release', defaultValue: '2.0.1-RC', description: 'Wersja publikacji')
        string(name: 'version_snapshot', defaultValue: '2.0.2', description: 'Wersja rozwojowa')
        string(name: 'YOUR_USERNAME', defaultValue: 'ubuntu')
        password(name: 'YOUR_PASSWORD', defaultValue: 'secret')
      }
    tools {
        jdk "JDK_1.8"
        maven "mvn_3.6.3"
    }
    stages {

        stage ('Prepare') {
          steps {
            echo 'Prepare..'
            cleanWs()
            checkout scm

//             script {
//                 if (runShell('grep \''+version_release+'\' collector/build.gradle')) {
//                     echo 'wersja bez zmian!'
//                 } else {
//                     sh "sed 's/version=.*/version=\""+ version_release+"\"/g' collector/build.gradle > collector/build.gradle.tmp"
//                     sh 'mv collector/build.gradle.tmp collector/build.gradle'
//                 }
//             }
          }
        }
        stage('Build') {
            steps {
                echo 'Building..'
                script {
                    try {
                        sh "mvn -Dmaven.test.failure.ignore=true clean package -Pmegapack -f service/pom.xml"
                    } finally { //Make checkstyle results available
                        //checkstyle canComputeNew: false, defaultEncoding: '', healthy: '', pattern: 'publicapi/frontend/tslint-result.xml', unHealthy: ''
                    }
                }
            }
        }
        stage('Test') {
            steps {
                echo 'Testing..'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying....'
                sh 'echo "[webserver]" > hosts_tmp.yml'
                sh 'echo "e-strix.pl ansible_host=51.83.132.174 ansible_user=${YOUR_USERNAME} ansible_ssh_pass=${YOUR_PASSWORD} ansible_sudo_pass=${YOUR_PASSWORD}" >> hosts_tmp.yml'

                sh 'ansible-playbook service/playbook_rc.yml -i hosts_tmp.yml --extra-vars "version=${version_release}"'

            }
        }
    }
}
