---
- name: This is a hello-world example
  hosts: webserver
  become: true
  tasks:
    - name: Copy WAR to server
      copy:
        src: return-parcel-app/target/return-parcel-app.war
        dest: /var/www/e-strix.pl/public_html/megapack/ROOT_{{ version }}.war
    - name: Copy SQL to server
      copy:
        src: dump/update.sql
        dest: /var/www/e-strix.pl/public_html/megapack/update.sql