management:
  context-path: /sysinfo
spring:
    jpa:
        database: MYSQL
        show-sql: false
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5Dialect
                hbm2ddl:
                  import_files: import_data.sql
        hibernate:
            ddl-auto: update
    datasource:
        url: jdbc:mysql://localhost:3306/shipments?useUnicode=yes&characterEncoding=UTF-8
        username: root
        password: toor
        driver-class-name: com.mysql.jdbc.Driver
        testWhileIdle: true
        testOnBorrow: true
        validationQuery: SELECT 1
hibernate:
    archive:
        autodetection: class
logging:
    level:
        ROOT: ERROR
        org:
            springframework:
                data: DEBUG
            hibernate:
                type: DEBUG
        pl:
            estrix: DEBUG
    pattern:
        file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: logs/application.log
server:
    port : 8080
    session-timeout : 1800