management:
  context-path: /sysinfo
  endpoint:
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
spring:
    jpa:
        database: MYSQL
        show-sql: false
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5Dialect
                hbm2ddl:
                  import_files: import_data.sql
        hibernate:
            ddl-auto: update
    datasource:
        url: jdbc:mysql://mysql:3306/zwroty_e_strix_com?useUnicode=yes&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&useSSL=false
        username: user
        password: user
        driver-class-name: com.mysql.jdbc.Driver
        testWhileIdle: true
        testOnBorrow: true
        validationQuery: SELECT 1
hibernate:
    archive:
        autodetection: class
logging:
    level:
        ROOT: ERROR
        org:
            springframework:
                data: INFO
            hibernate:
                type: INFO
        pl:
            estrix: DEBUG
    pattern:
        file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: /opt/tomcat/logs/application.log
server:
#    port : 8080
    session-timeout : 1800