---
- name: This is a hello-world example
  hosts: webserver
  become: true
  tasks:
    - name: Copy APK to server
      copy:
        src: android/app/build/outputs/apk/debug/app-debug.apk
        dest: /var/www/e-strix.pl/public_html/megapack/megafind_{{ version }}.apk