pipeline {
    agent any
    tools {
        gradle "Gradle_4.6"
    }
    stages {
        stage('Build') {
            steps {
                echo 'Building..'
                script {
                    try {
                        sh 'cd collector'
                        sh 'gradle android'
                    } finally { //Make checkstyle results available
                        //checkstyle canComputeNew: false, defaultEncoding: '', healthy: '', pattern: 'publicapi/frontend/tslint-result.xml', unHealthy: ''
                    }
                }
            }
        }
        stage('Test') {
            steps {
                echo 'Testing..'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying....'
            }
        }
    }
}
