def runShell(String command){
    def responseCode = sh returnStatus: true, script: "${command} &> tmp.txt"
    def output =  readFile(file: "tmp.txt")
    return (output != "")
}

def buildTime() {
    new Date().format('yyyy.MM.dd HH:mm')
}

pipeline {
    agent any
    environment {
        ANDROID_HOME= "/Users/kamilmucik/Library/Android/sdk"
        ANDROID_SDK_ROOT= "/Users/kamilmucik/Library/Android/sdk"
        ANDROID_AVD_HOME= "/Users/kamilmucik/.android/avd"
        PATH = "$PATH:$ANDROID_HOME/sdk:$ANDROID_HOME/tools:/usr/local/bin"
      }

    parameters {
        string(name: 'version_release', defaultValue: '2.0.1-RC', description: 'Wersja publikacji')
        string(name: 'version_snapshot', defaultValue: '2.0.2', description: 'Wersja rozwojowa')
        string(name: 'YOUR_USERNAME', defaultValue: 'ubuntu')
        password(name: 'YOUR_PASSWORD', defaultValue: 'secret')
      }
    tools {
        gradle "Gradle_4.6"
    }
    stages {

        stage ('Prepare') {
          steps {
            echo 'Prepare..'
            cleanWs()
            checkout scm

            script {
                if (runShell('grep \''+version_release+'\' collector/build.gradle')) {
                    echo 'wersja bez zmian!'
                } else {
                    sh "sed 's/version=.*/version=\""+ version_release+"\"/g' collector/build.gradle > collector/build.gradle.tmp"
                    sh 'mv collector/build.gradle.tmp collector/build.gradle'
                }
            }
          }
        }
        stage('Build') {
            steps {
                echo 'Building..'
                script {
                    try {
                        sh 'mkdir -p collector/build/resources/android/'
                        sh 'echo "estrix.application.biuld-time='buildTime()'" > collector/build/resources/android/filter.properties'
                        sh 'echo "estrix.application.versio2n=${version_release}" >> collector/build/resources/android/filter.properties'
                        sh 'gradle clean android -b collector/build.gradle'
                    } finally { //Make checkstyle results available
                        //checkstyle canComputeNew: false, defaultEncoding: '', healthy: '', pattern: 'publicapi/frontend/tslint-result.xml', unHealthy: ''
                    }
                }
            }
        }
        stage('Test') {
            steps {
                echo 'Testing..'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying....'
                sh 'echo "[webserver]" > hosts.yml'
                sh 'echo "e-strix.pl ansible_host=51.83.132.174 ansible_user=${YOUR_USERNAME} ansible_ssh_pass=${YOUR_PASSWORD} ansible_sudo_pass=${YOUR_PASSWORD}" >> hosts.yml'

                sh 'ansible-playbook collector/playbook_rc.yml -i hosts.yml --extra-vars "version=${version_snapshot}"'

//                 sh 'rm -rf android/app/src/main/res/drawable-*'
//                 sh 'echo "${version_release}" > version.properties'
//                 sh 'git add version.properties'
//                 sh 'git commit -m "Update version"'
//                 sh 'git push origin HEAD:master'
            }
        }
    }
}
