pipeline {
    agent any
    environment {
        ANDROID_HOME= "/Users/kamilmucik/Library/Android/sdk"
        ANDROID_SDK_ROOT= "/Users/kamilmucik/Library/Android/sdk"
        ANDROID_AVD_HOME= "/Users/kamilmucik/.android/avd"
        PATH = "$PATH:$ANDROID_HOME/sdk:$ANDROID_HOME/tools"
      }

    parameters {
        string(name: 'version_release', defaultValue: '2.0.0', description: 'Wersja publikacji')
        string(name: 'version_snapshot', defaultValue: '2.0.1-RC', description: 'Wersja rozwojowa')
        string(name: 'YOUR_USERNAME', defaultValue: 'ubuntu')
        password(name: 'YOUR_PASSWORD', defaultValue: 'secret')
      }
    tools {
        gradle "Gradle_4.6"
    }
    stages {

        stage ('Prepare') {
          steps {
            echo "PATH is: $PATH"
          }
        }
        stage('Build') {
            steps {
                echo 'Prepare..'
                cleanWs()
                checkout scm
                echo 'Building..'
                script {
                    try {
                        sh 'gradle clean android -b collector/build.gradle'
                    } finally { //Make checkstyle results available
                        //checkstyle canComputeNew: false, defaultEncoding: '', healthy: '', pattern: 'publicapi/frontend/tslint-result.xml', unHealthy: ''
                    }
                }
            }
        }
        stage('Test') {
            steps {
                echo 'Testing..'
            }
        }
        stage('Deploy') {
            steps {
                sh 'ansible -v'
                echo 'Deploying....'
                sh 'echo "e-strix.pl ansible_host=51.83.132.174 ansible_user=${YOUR_USERNAME} ansible_ssh_pass=${YOUR_PASSWORD} ansible_sudo_pass=${YOUR_PASSWORD}" >> collector/hosts.yml'

                sh 'ansible-playbook collector/playbook_rc.yml -i collector/hosts.yml --extra-vars "version=${version_snapshot}"'

//                 sh 'rm -rf android/app/src/main/res/drawable-*'
//                 sh 'echo "${version_release}" > version.properties'
//                 sh 'git add version.properties'
//                 sh 'git commit -m "Update version"'
//                 sh 'git push origin HEAD:master'
            }
        }
    }
}
